
# Links Kubernetes ServiceAccount to AWS IAM role for pod-level permissions
# Pods using this ServiceAccount automatically get AWS credentials

apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: default
  annotations:
    # IRSA annotation - IAM role that pods can assume
    # EKS injects AWS credentials when pods use this ServiceAccount
    eks.amazonaws.com/role-arn: unleash-exercise-cluster-app-role
